### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by meap158** [ACK72/kavya-paperback#3] opened 2023-03-20 05:03 UTC
**Describe the bug**
Downloading manga not working (downloading wont start)

For new manga that are not already in my Library, it’s hit or miss, some will start downloading some will not.

But downloading ones in library it will just not star downloading at all. (mostly the ones that I tried to download before your new update)

**To Reproduce**
1. Download any manga

**Expected behavior**
- Manga are added to the download queue and start downloading

**Screenshots**
![image](https://user-images.githubusercontent.com/14327094/226250433-e6681488-48aa-4aa7-ba93-ea29411182ed.png)

**Additional logs**
Paperback log files are a great help in identifying and resolving issues.

Log files contain sensitive information such as server address and API key,
so please send them via <ack72.github@gmail.com>.
And it is recommended to change related API key.

You can get app logs at paperback settings > export app logs,
and extension logs at paperback settings > external sources > Kavya > share logs.

**Comment by ACK72** [comment] 2023-03-20 05:29
Well, Kavya log doesnt seems to be helpful.
Could you please send me a app(paperback) log again?
It can be found at paperback settings > export app logs.

**Comment by ACK72** [comment] 2023-03-26 13:52
I can't reproduce this issue, so I'll close it for now.
If it is the same after checking the settings, please re-create the issue.

**Closed as completed by ACK72** 2023-03-26 13:52 UTC
