### ISSUE TITLE
[BUG] Archive images not loading

### ISSUE THREAD

**Issue by therobbiedavis** [ACK72/kavya-paperback#1] opened 2023-02-18 18:57 UTC
**Describe the bug**
When I click to read a chapter in the extension no images are loaded

**To Reproduce**
1. Go to Series
2. Click on Chapter 1
3. See no images loaded

**Expected behavior**
Images are loaded

**Screenshots**
![IMG_6170](https://user-images.githubusercontent.com/7907265/219882864-46f293d4-0aa1-4f47-88a1-cd83a3cea0e8.png)
![IMG_6171](https://user-images.githubusercontent.com/7907265/219882865-5c47e12a-8b91-42ad-aed7-3a668d199308.png)
![IMG_6172](https://user-images.githubusercontent.com/7907265/219882867-4cd95e0d-2154-44b0-ab1b-620f08c9ca9a.png)
The XML of from https://kavita.[REDACTED]/api/opds/[REDACTED]series/4451/volume/13241/chapter/131229
![image](https://user-images.githubusercontent.com/7907265/219883345-a633a8ac-544b-4b7d-8355-d1aa43263c25.png)

**Additional logs**
[18-02.Paperback.txt](https://github.com/ACK72/paperback-extension/files/10774958/18-02.Paperback.txt)
I've redacted the sensitive information

**Comment by therobbiedavis** [comment] 2023-02-18 19:01
It looks to be using the wrong series ID, and the chapter ID for the volume ID in the OPDS url call:
`https://kavita.[REDACTED]/api/opds/[REDACTED]/series/**4**/volume/**131229**/chapter/**131229**`
When it should be:
`https://kavita.[REDACTED]/api/opds/[REDACTED]/series/4451/volume/13241/chapter/131229`

**Comment by ACK72** [comment] 2023-02-18 19:03
I guess this bug is caused by a mismatch between volumeId and chapterId.
Currently, this plugin assumes volumeId and chapterId are the same.

I'm planning to remove the implementation of opds soon and re-implement it with kavita api.
It will fix this issue. Thanks for reporting the bug.

**Comment by ACK72** [comment] 2023-02-19 11:16
The newer version of Kavya with Kavita API has been released. Hopefully it fixes this issue.
I'll close this issue now. If you still have issues, please file an issue again.

By the way, there seems to be a paperback issue with the extension version not displaying properly.
You might need to re-install paperback.

![IMG_0744](https://user-images.githubusercontent.com/25812442/219944465-6e4b8979-4c88-44ac-8552-f0de413fc21d.PNG)

**Closed as completed by ACK72** 2023-02-19 11:16 UTC
